### ISSUE TITLE
[Issue] Fionna can't detect device in my mac

### ISSUE THREAD

**Issue by binhdao112** [omsage/fionna#4]
Hi sir, I know fionna from testerhome 😁 after download and start it, I meet a issue, i don't know it's bug or issue from my installation 
---
Looking forward to your help
---
<img width="1075" alt="Screenshot 2024-07-09 at 17 16 00" src="https://github.com/omsage/fionna/assets/54032190/d90bf559-bba1-4c58-b672-96fcdebe7c09">

**Comment by ZhouYixun** [comment]
what is your `adb devices` output?

**Comment by binhdao112** [comment]
> what is your `adb devices` output?

This is my `adb devices` output 💯 
<img width="312" alt="Screenshot 2024-07-10 at 09 32 05" src="https://github.com/omsage/fionna/assets/54032190/8ea7cdc6-67fa-4e93-b896-30aa9aaa7a29">

**Comment by aoliaoaoaojiao** [comment]
It seems to be an issue with a low-level dependency package. I'll try to address it, but I can't guarantee its effectiveness since I don't have a Mac. I'll create a separate branch and build artifacts specifically for output. If possible, could you assist in testing it? @binhdao112

**Comment by aoliaoaoaojiao** [comment]
If possible, I'd also like to know the version of adb.

**Comment by aoliaoaoaojiao** [comment]
The 0.0.9 version has attempted to fix it, you can give it a try

**Comment by binhdao112** [comment]
> It seems to be an issue with a low-level dependency package. I'll try to address it, but I can't guarantee its effectiveness since I don't have a Mac. I'll create a separate branch and build artifacts specifically for output. If possible, could you assist in testing it? @binhdao112

It is my honor to contribute to the project ^^

**Comment by binhdao112** [comment]
> The 0.0.9 version has attempted to fix it, you can give it a try

oke i will try it

**Comment by binhdao112** [comment]
> The 0.0.9 version has attempted to fix it, you can give it a try

It started and worked in my mac. Thanks @aoliaoaoaojiao so much

**Comment by aoliaoaoaojiao** [comment]
> It started and worked in my mac. Thanks @aoliaoaoaojiao so much

ok.
Tips: Please use Google Chrome on macOS. The native macOS browser does not support the H.264 decoding library.😁

**Comment by binhdao112** [comment]
> > It started and worked in my mac. Thanks @aoliaoaoaojiao so much
> 
> ok. Tips: Please use Google Chrome on macOS. The native macOS browser does not support the H.264 decoding library.😁

But @aoliaoaoaojiao , Can i ask you a quesion ^^ My mobile device only supports 60 frames per second but while running fionna, there are data of 61 fps, is it correct?

**Comment by aoliaoaoaojiao** [comment]
Yes, this is a known issue that I've been aware of since the initial release. Currently, there is a slight frame offset of about one frame. I attempted to fix this issue previously but encountered significant problems, so I reverted the relevant code back to version 0.0.8.

**Comment by aoliaoaoaojiao** [comment]
> But @aoliaoaoaojiao , Can i ask you a quesion ^^ My mobile device only supports 60 frames per second but while running fionna, there are data of 61 fps, is it correct?

Yes, this is a known issue that I've been aware of since the initial release. Currently, there is a slight frame offset of about one frame. I attempted to fix this issue previously but encountered significant problems, so I reverted the relevant code back to version 0.0.8.

**Comment by binhdao112** [comment]
> > But @aoliaoaoaojiao , Can i ask you a quesion ^^ My mobile device only supports 60 frames per second but while running fionna, there are data of 61 fps, is it correct?
> 
> Yes, this is a known issue that I've been aware of since the initial release. Currently, there is a slight frame offset of about one frame. I attempted to fix this issue previously but encountered significant problems, so I reverted the relevant code back to version 0.0.8.

okie thanks @aoliaoaoaojiao so much ^^ I will close ticket

**Comment by aoliaoaoaojiao** [comment]
> okie thanks @aoliaoaoaojiao so much ^^ I will close ticket

The original plan was to try to resolve it over the weekend. So, if you can wait until the weekend, that would be fine.

**Comment by binhdao112** [comment]
> > okie thanks @aoliaoaoaojiao so much ^^ I will close ticket
> 
> The original plan was to try to resolve it over the weekend. So, if you can wait until the weekend, that would be fine.

okie, It's nice to hear that, I'll wait until the weekend ^^

**Comment by aoliaoaoaojiao** [comment]
> 
> okie, It's nice to hear that, I'll wait until the weekend ^^

Okay, the new version has resolved it. You can give it a try.

**Comment by binhdao112** [comment]
> > okie, It's nice to hear that, I'll wait until the weekend ^^
> 
> Okay, the new version has resolved it. You can give it a try.

Okay, i tried it , it work very well and the data seems to be more accurate 😁 thanks fen so much
