### ISSUE TITLE
无法获取 FPS

### ISSUE THREAD

**Issue by CainsLee** [omsage/fionna#8]
![image](https://github.com/user-attachments/assets/6f3a4f9e-55fb-4b4a-91d4-b71c7ef75457)
无法获取 FPS 数据，其他数据正常。
请问是我的哪个步骤有问题吗，谢谢。

time="2024-10-27T10:18:15+08:00" level=info msg="client send close perf info,close perf..."
time="2024-10-27T10:18:17+08:00" level=info msg="java.lang.NoSuchMethodError: no static method \"Landroid/view/SurfaceControl;.createDisplay(Ljava/lang/String;Z)Landroid/os/IBinder;\"\n\tat com.omsage.PerfTool.Frame.streamScreenNative(Native Method)\n\tat com.omsage.PerfTool.Frame.lambda$start$0$com-omsage-PerfTool-Frame(Frame.java:24)\n\tat com.omsage.PerfTool.Frame$$ExternalSyntheticLambda0.run(Unknown Source:4)\n\tat java.lang.Thread.run(Thread.java:1042)\n[perf-tool] ERROR: error139\n"
time="2024-10-27T10:18:17+08:00" level=error msg="frame output err,EOF"

**Comment by aoliaoaoaojiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/152052105/380463136-6f3a4f9e-55fb-4b4a-91d4-b71c7ef75457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODM2MDcsIm5iZiI6MTczMDA4MzMwNywicGF0aCI6Ii8xNTIwNTIxMDUvMzgwNDYzMTM2LTZmM2E0ZjllLTU1ZmItNGI0YS05MWQ0LWI3MWM3ZWY3NTQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwMjQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMThmYjg1Y2E2MWUxNDNkMTQ0M2I4YjljNmM4ZjVlNjMxOGJjODZiYzZjZDFjMGU0NmUzMGUwZThkMmFiYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YxJ6-KTGRVx4Jjmv0A_Y8YTHFNodJkp36GFyaFmPxfE) 无法获取 FPS 数据，其他数据正常。 请问是我的哪个步骤有问题吗，谢谢。
> 
> time="2024-10-27T10:18:15+08:00" level=info msg="client send close perf info,close perf..." time="2024-10-27T10:18:17+08:00" level=info msg="java.lang.NoSuchMethodError: no static method "Landroid/view/SurfaceControl;.createDisplay(Ljava/lang/String;Z)Landroid/os/IBinder;"\n\tat com.omsage.PerfTool.Frame.streamScreenNative(Native Method)\n\tat com.omsage.PerfTool.Frame.lambda$start$0$com-omsage-PerfTool-Frame(Frame.java:24)\n\tat com.omsage.PerfTool.Frame$$ExternalSyntheticLambda0.run(Unknown Source:4)\n\tat java.lang.Thread.run(Thread.java:1042)\n[perf-tool] ERROR: error139\n" time="2024-10-27T10:18:17+08:00" level=error msg="frame output err,EOF"

新的采集帧数据方法兼容性有问题，后面会加入传统的SurfaceFlinger和GFXInfo方法

**Comment by CainsLee** [comment]
谢谢
